# Generated by Django 2.0.7 on 2018-08-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='ques',
        ),
        migrations.AddField(
            model_name='set',
            name='ques',
            field=models.ManyToManyField(to='OnlineExamination.Question'),
        ),
    ]
